-- nvim key maps
vim.keymap.set("i", "<C-l>", "<ESC>", {})
vim.keymap.set("n", "ii", "$", {})
vim.keymap.set("n", "uu", "0", {})
vim.keymap.set("n", "nn", "gg", {})
vim.keymap.set("n", "mm", "G", {})
vim.keymap.set("v", "<C-l>", "<ESC>", {})
vim.keymap.set("v", "ii", "$", {})
vim.keymap.set("v", "uu", "0", {})
vim.keymap.set("v", "nn", "gg", {})
vim.keymap.set("v", "mm", "G", {})
vim.cmd("set expandtab")
vim.cmd("set tabstop=2")
vim.cmd("set softtabstop=2")
vim.cmd("set shiftwidth=2")
